### ISSUE TITLE
Expand fully qualified with leading \

### ISSUE THREAD

**Issue by Nizari** [erichard/SublimePHPCompanion#101]
I have my keybinding for fqcn:  _{"keys": ["f8"], "command": "expand_fqcn" },_

However, I can't seem to to find a way to use expand_fqcn with a leading \.
How would I set this up? it should be possible according to the docs.

p.s. this tool is amazing!

**Comment by winnie131212592** [comment]
this to turret try yet tree were utter bmdn CTV via this tryrutttn
Jmllkiyt5iy5
 2wchñ
Gmmb

**Comment by wbgneto** [comment]
`{ "keys": ["f8"], "command": "expand_fqcn", "args": {"leading_separator": true} },`
