### ISSUE TITLE
Feature request: Support for "use function" in find_use

### ISSUE THREAD

**Issue by ezzatron** [erichard/SublimePHPCompanion#104]
Since PHP 5.6, `use function` (and `use const`) are available. Would it be possible to add support for functions in `find_use`?

The rules are pretty much identical to those used for importing classes, but PHP Companion would need to know whether the symbol was a function or not.

**Comment by claudiodaud** [comment]
Uninstall and reinstall the latest version 4169 of ST4 and package control, everything will work again

![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/730d0899-7f2c-453a-958e-7fb994c8c05a)
![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/8ede0e6d-36bc-4e80-b3e5-05f951fc98eb)
![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/9f65f225-fa21-4345-b800-d388d55e81b5)
