### ISSUE TITLE
Feature request: When sorting use statements, match the sort order typically used by php-cs-fixer

### ISSUE THREAD

**Issue by ezzatron** [erichard/SublimePHPCompanion#105]
When adding use statements to a file as a result of `find_use`, PHP Companion inserts the use statement where it should appear in alphabetical order (seemingly using the top-most namespace only?).

This is pretty good already, but it's not a perfect fit to how use statements are ordered by [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)'s "ordered_imports" fixer.

The exact logic they use is (from [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.6/src/Fixer/Import/OrderedImportsFixer.php#L258)):

```php
    private function sortAlphabetically(array $first, array $second)
    {
        if ($first['importType'] !== $second['importType']) {
            return $first['importType'] > $second['importType'] ? 1 : -1;
        }

        // Replace backslashes by spaces before sorting for correct sort order
        $firstNamespace = str_replace('\\', ' ', $this->prepareNamespace($first['namespace']));
        $secondNamespace = str_replace('\\', ' ', $this->prepareNamespace($second['namespace']));

        return strcasecmp($firstNamespace, $secondNamespace);
    }
```

So the important details here are:

1. The sort is case-insensitive, whereas PHP Companion appears to sort in a case-sensitive manner, putting uppercase letters above lowercase.
2. Rather than sorting just the first part of a namespace, backslashes are replaced with spaces before sorting the entire string.
3. Different import "types" (`use`, `use function`, `use const`) are treated as different lists for sorting. Another way of saying this is that the use statements are sorted by type first. This is irrelevant to PHP Companion right now, but would relate to #104 if implemented.

**Comment by erichard** [comment]
I think PHP Companion should not care of the use sorting. php-cs-fixer does that pretty well, no need to reinvent the wheel.

**Comment by arxeiss** [comment]
@erichard I don't understand why this is closed... In our new project, company set rules and one of them is sorting `use` alphabetically but case insensitive. Now I cannot use your tool, because there are permanent changes in git.

Why this package should not contain option to turn on/off case insensitive sorting?

**Comment by erichard** [comment]
@arxeiss PHP Companion need a default sorting algorithm but not a full sorting feature that php-cs-fixer does very well. 

You might want to try [PHPCS](https://packagecontrol.io/packages/Phpcs) plugin to execute php-cs-fixer on save and get rid of your git problem.
