### ISSUE TITLE
how to find who inherits an interface or class ? 

### ISSUE THREAD

**Issue by videni** [erichard/SublimePHPCompanion#109]
I need this feature badly,  because my project is very big , find the descendants of a class or interface , can save us lots of time.

**Comment by erichard** [comment]
Hi, can you explain a bit further ? 

Let say your cursor is on a classname and you hit the key that map to your feature, then the quickpanel display a list of descendants, what do you want to do with them ? select one and open it ?

**Comment by videni** [comment]
@erichard , the quickpanel doesn't show,   you mean this package has this feature already,  but I never see anything shows it works.

**Comment by erichard** [comment]
@videni No the feature does not exists. I try to figure what it the use case and how it should behave.
