### ISSUE TITLE
Latest PHP Companion release breaks "Find Use"

### ISSUE THREAD

**Issue by taylorotwell** [erichard/SublimePHPCompanion#113]
Doesn't seem to work at all for me anymore on 1.4.1 release.

**Comment by taylorotwell** [comment]
Actually looks like it was 1.4.0 that broke it. Downgrading to 1.3.2 fixed.

**Comment by xudong7930** [comment]
I have same problem

**Comment by erichard** [comment]
Yeah sorry for that. I'm aware of the problem but I don't know yet how to fix it :(

**Comment by keevitaja** [comment]
https://github.com/erichard/SublimePHPCompanion/issues/76

perhaps my last comment there helps

**Comment by weimindong2016** [comment]
same issue here. I am using the 1.4.4 version on windows 10.  Any update on the plan to fix this issue in the future?

**Comment by cbloss** [comment]
I'm in the same boat. Latest update broke the `find_use`. Version 1.4.4

**Comment by cbloss** [comment]
I uninstalled, re-installed, opened and closed Sublime a couple times. A couple hours later, it started working again. I have no idea why.

**Comment by Lykegenes** [comment]
What fixed it for me was closing all the opened projects and then closing Sublime. Then I simply deleted all the index files in `~/Library/Application Support/Sublime Text 3/Index` and reopened Sublime and my projects. 
When the indexing was finished, everything was working again.

**Comment by ipontt** [comment]
Thanks for the fox @Lykegenes . It worked for me. In Windows, the Index folder is located in `Users\{user}\AppData\Local\Sublime Text 3\Index`

**Comment by jonjieviduya** [comment]
Hi @taylorotwell, how did you downgrade it to that version?

**Comment by claudiodaud** [comment]
Uninstall and reinstall the latest version 4169 of ST4 and package control, everything will work again

**Comment by claudiodaud** [comment]
![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/fed3d431-8f04-4735-8919-ae681d478f84)
![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/cb069e80-beb5-4f8a-b177-ccbc350a44b1)
![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/9128ce91-e2fe-468b-8a81-4e5cefb5627b)
