### ISSUE TITLE
 insert_php_constructor_property keeps jumping back to first class

### ISSUE THREAD

**Issue by francois-auclair** [erichard/SublimePHPCompanion#115]
Hi

If i have multiple class in one file, 

whenever I try to run the **insert_php_constructor_property** , it jumps back to the first class at top of the file and inserts another argument.

Any hint ?

**Comment by erichard** [comment]
Hi @francoboy7 

This feature does not support multiple classe in the same file.

**Comment by francoboy7** [comment]
Thanks for the reply ;)
