### ISSUE TITLE
Show a popup when importing a use namespace

### ISSUE THREAD

**Issue by predragnikolic** [erichard/SublimePHPCompanion#122]
Showing a popup when importing a use namespace gives more obvious feedback than showing it in the status bar. 

![output](https://user-images.githubusercontent.com/22029477/41817643-6d324ad8-779f-11e8-931f-917b21a6f82d.gif)

What do you think?

**Comment by erichard** [comment]
@predragnikolic Better experience than the status bar. Do you want to make a PR ?

Off topic but what theme/colorscheme do you use ? It look great

**Comment by predragnikolic** [comment]
I will make a PR in a minute.
In package control, type `Panda Syntax Sublime` :)
