### ISSUE TITLE
Curiosity

### ISSUE THREAD

**Issue by gabriel-flores** [erichard/SublimePHPCompanion#125]
Hi @erichard, how are you doing?

I was reading your README.md before trying the package and saw that you switched to vim.
As I'm a ST and vim user I wonder why you choose to switch to vim. Can you have better code completion with php through vim? If yes, can you say how? ctags of something like that?

Thanks in advance =)

**Comment by erichard** [comment]
Hi @gabrieltigre. Sorry for my late response. 

In fact I'm still in the process of switching, it's so hard to change our code habits! I have a very good efficiency with ST but I try to push further. 

I'm not a huge fan of completion but I use [lvht/phpcd.vim](https://github.com/lvht/phpcd.vim) for core PHP completion and [universal ctags](https://ctags.io/) for project related completion. 

What I really use is snippets, keybinding and macro. Vim is pretty good for all of this, so I'm trying, I really do :smile:
