### ISSUE TITLE
import_namespace stopped working

### ISSUE THREAD

**Issue by remi-blaise** [erichard/SublimePHPCompanion#142]
Hi!

I have been using this package for years. The import_namespace stopped working a few days ago.
Using the command from the Command Palette neither work.

The find_use is still working.

Any idea?

PS: Maybe since I upgraded to PHP 7.4?

**Comment by erichard** [comment]
Hi Remi,

Do you have any error message in the console view ?

**Comment by antoniodesa** [comment]
Same here, no console error message.

**Comment by erichard** [comment]
Ok. Still working for me on php 7.4.

You can try to purge your index by removing all files in the Index folder in your data folder :
  
    OS X: ~/Library/Application Support/Sublime Text 3/Index/
    Windows: %APPDATA%\Sublime Text 3/Index/
    Linux: ~/.config/sublime-text-3/Index/

**Comment by dinhquochan** [comment]
@erichard Not work on ST4 :) 
![image](https://user-images.githubusercontent.com/9979458/102018005-1962d780-3d9d-11eb-8a39-548191ab4776.png)

**Comment by dinhquochan** [comment]
@erichard just tested, only import_namespace: is not work.

**Comment by erichard** [comment]
Didn't know ST4 was a thing ! It's only a closed alpha for now so I will look for a proper support when it come to beta

**Comment by jinjie** [comment]
ST4 is now available. I got this error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/Users/***/Library/Application Support/Sublime Text/Installed Packages/PHP Companion.sublime-package/php_companion/commands/import_namespace_command.py", line 22, in run
  File "/Users/***/Library/Application Support/Sublime Text/Installed Packages/PHP Companion.sublime-package/php_companion/utils.py", line 85, in get_namespace
KeyError: 'autoload'
```

**Comment by serv101** [comment]
> ST4 is now available. I got this error:
> 
> ```
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
>     return self.run(edit)
>   File "/Users/***/Library/Application Support/Sublime Text/Installed Packages/PHP Companion.sublime-package/php_companion/commands/import_namespace_command.py", line 22, in run
>   File "/Users/***/Library/Application Support/Sublime Text/Installed Packages/PHP Companion.sublime-package/php_companion/utils.py", line 85, in get_namespace
> KeyError: 'autoload'
> ```
> 
> ### EDIT
> My mistake. ST4 seem to not index directories / files in .gitignore. I have added the below in preferences for it to work.
> 
> ```json
> {
>     "index_exclude_gitignore": false
> }
> ```

Thank you @jinjie that worked. I did that and also added node_modules to folder exclude patterns since that was in .gitignore as well i do'nt need it to index that:
`
"folder_exclude_patterns": [".svn", ".git", ".hg", "CVS", ".Trash", ".Trash-*", "node_modules"],
"index_exclude_gitignore": false
`

**Comment by importjeremy** [comment]
> ST4 is now available. I got this error:
> 
> ```
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
>     return self.run(edit)
>   File "/Users/***/Library/Application Support/Sublime Text/Installed Packages/PHP Companion.sublime-package/php_companion/commands/import_namespace_command.py", line 22, in run
>   File "/Users/***/Library/Application Support/Sublime Text/Installed Packages/PHP Companion.sublime-package/php_companion/utils.py", line 85, in get_namespace
> KeyError: 'autoload'
> ```
> 
> ### EDIT
> My mistake. ST4 seem to not index directories / files in .gitignore. I have added the below in preferences for it to work.
> 
> ```json
> {
>     "index_exclude_gitignore": false
> }
> ```

Thanks @jinjie that worked for me also! I noticed since node_modules is in .gitignore it started indexing that after that change. So I updated it to:

```json
{
     "index_exclude_patterns": ["*.log", "node_modules/*"],
     "index_exclude_gitignore": false,
}
```

**Comment by seivad** [comment]
> ST4 is now available. I got this error:
> 
> ```
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
>     return self.run(edit)
>   File "/Users/***/Library/Application Support/Sublime Text/Installed Packages/PHP Companion.sublime-package/php_companion/commands/import_namespace_command.py", line 22, in run
>   File "/Users/***/Library/Application Support/Sublime Text/Installed Packages/PHP Companion.sublime-package/php_companion/utils.py", line 85, in get_namespace
> KeyError: 'autoload'
> ```
> 
> ### EDIT
> My mistake. ST4 seem to not index directories / files in .gitignore. I have added the below in preferences for it to work.
> 
> ```json
> {
>     "index_exclude_gitignore": false
> }
> ```

This is the fix... what an absolute pain that this changed after years! I was almost contemplating using VSCode

**Comment by remi-blaise** [comment]
Hi!

Thank you for all your answers.

So I opened the console, it said:
```
Traceback (most recent call last):
  File "/snap/sublime-text/97/opt/sublime_text/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/home/remi/.config/sublime-text-3/Installed Packages/PHP Companion.sublime-package/php_companion/commands/import_namespace_command.py", line 22, in run
  File "/home/remi/.config/sublime-text-3/Installed Packages/PHP Companion.sublime-package/php_companion/utils.py", line 84, in get_namespace
  File "/home/remi/.config/sublime-text-3/Installed Packages/PHP Companion.sublime-package/php_companion/utils.py", line 81, in get_composer
FileNotFoundError: [Errno 2] No such file or directory: '/home/remi/.config/sublime-text-3/Packages/PHP Companion/composer.json'
```

@erichard I tried `rm ~/.config/sublime-text-3/Index/*`, did not solve
@jinjie I added `"index_exclude_gitignore": false`, did not solve the problem (I am on ST3)

@erichard By reading the error, I think PHP Companion is looking for composer.json in the wrong place, don't you think?

**Comment by quarkmarino** [comment]
In my case, my composer.json file had an an extra comma which made it invalid, not sure if phpcompanion needs it for looking for the right namespace classes path, I discovered that composer.json was invalid by running `composer dump-autoload` and it reported it, once fixed, the `import_namespace` worked again.

**Comment by claudiodaud** [comment]
Uninstall and reinstall the latest version 4169 of ST4 and package control, everything will work again

![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/730d0899-7f2c-453a-958e-7fb994c8c05a)
![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/8ede0e6d-36bc-4e80-b3e5-05f951fc98eb)
![image](https://github.com/erichard/SublimePHPCompanion/assets/43547931/9f65f225-fa21-4345-b800-d388d55e81b5)

**Comment by touson** [comment]
None of this worked for me.  I've reset Sublime Text 4 by removing the ~/Library/Caches/Sublime Text directory and rebooting ST4.

After the reboot, the index repopulates.  I've then reinstalled the PHPCompanion package and added the below to my settings file: -

`"index_exclude_gitignore": false,`

Rebooted ST4, but the `import_namespace` in PHPCompanion still doesn't work.  All other functions of this package seem to work OK.

I'm running build 4200 of ST4.

Anyone got any idea's how I can resolve this as it's driving me nuts!?
