### ISSUE TITLE
Only "find_use" command works, while others don't???

### ISSUE THREAD

**Issue by quyle92** [erichard/SublimePHPCompanion#144]
Hi Richard,
I am using PHPCompanion for my laravel project. My text editor is sublime text 3.
But I don't understand why other commands, apart from "find_use", like expand_fqcn, goto_definition_scope, etc... does not work?
I've tried it using both default command hot keys and command palatte, but to no avail.
Can you please help?

**Comment by FdelS** [comment]
Same happens to me, only this three works:
implement
goto_definition_scope
insert_php_constructor_property

**Comment by quyle92** [comment]
Anyone can help us please???

**Comment by qarabaqi** [comment]
Maybe it helps:
https://github.com/erichard/SublimePHPCompanion/issues/145
