### ISSUE TITLE
Companion doesn't load most namespaces in laravel

### ISSUE THREAD

**Issue by qarabaqi** [erichard/SublimePHPCompanion#145]
Hey guys.
i newly installed Sublime (Build 4107) and enjoyed using it. But when i want to use commands working with namespaces (like fcqn) the package doesn't import most namespaces (i have defined keys). But for namespaces and classes like Response and DB it's not working.
i don't know what is the problem and how to fix it. maybe related to the companion not updated for years!

**Comment by erichard** [comment]
Hi @qarabaqi,

ST4 does not index files and folders ignored by .gitignore. Try to change your settings with 

```
    "index_exclude_gitignore": false
```

Companion does not need updates as it works flawlessly for years :wink:

**Comment by qarabaqi** [comment]
> Hi @qarabaqi,
> 
> ST4 does not index files and folders ignored by .gitignore. Try to change your settings with
> 
> ```
>     "index_exclude_gitignore": false
> ```
> 
> Companion does not need updates as it works flawlessly for years wink

Thank you so much. Solved a days consuming problem. just seems weird because i couldn't find the solution with google!
Anyway putting `"index_exclude_gitignore": false` in the project settings file eliminated the problem. i didn't even rebuild the cache!

**Comment by lucianene** [comment]
Thank you guys, had the same problem.

**Comment by erichard** [comment]
Good idea @arxeiss. I've updated the README.
