### ISSUE TITLE
Stopped working, can't reinstall

### ISSUE THREAD

**Issue by subdesign** [erichard/SublimePHPCompanion#149]
Somehow PHP Companion stopped working for me, even I used it for years. So I decided to uninstall then reinstall, but package control autocomplete doesn't suggest/find the package anymore. Is it only me, or?

Sublime Text 4 (4143) MacOS

<img width="510" alt="Screenshot 2023-02-03 at 16 51 22" src="https://user-images.githubusercontent.com/691695/216646460-7ea4166d-f98e-46dc-be91-7ee40ce97cff.png">

**Comment by erichard** [comment]
Hello @subdesign 

Don't know what happened to your install. The package is still referenced on package control and more than 30 persons have installed it today : https://packagecontrol.io/packages/PHP%20Companion

Maybe something is corrupted and you need to try with a fresh install of sublime text.

**Comment by subdesign** [comment]
> Hello @subdesign
> 
> Don't know what happened to your install. The package is still referenced on package control and more than 30 persons have installed it today : https://packagecontrol.io/packages/PHP%20Companion
> 
> Maybe something is corrupted and you need to try with a fresh install of sublime text.

possibly. meantime I realised sometimes works in specific projects, other times not. maybe it's with indexing of projects or such. 
yes, reinstall should help for this case imho.
thanks
