### ISSUE TITLE
Feature request: Remove unused imports

### ISSUE THREAD

**Issue by syntheticminds** [erichard/SublimePHPCompanion#151]
Great plugin. I mainly use it for the Find use command.

However, when I've refactored a class, I'm often left with lots of imports I no longer need. It would be cool if there was a command that looks at the script to find imports that aren't being used and removes them.

Many thanks for such a useful plugin.

**Comment by erichard** [comment]
Thanks @syntheticminds 

It will be best done by php-cs-fixer. You can use a sublime plugin that run the fixer on each save for example.

I personally use this one : https://benmatselby.dev/sublime-phpcs/

php-cs-fixer can remove unused imports and much more thing to clean your files.

**Comment by syntheticminds** [comment]
Ah ha. I'm only using the coding standards part of it. I'll check out the php-cs-fixer options. Thanks!
