### ISSUE TITLE
Default keymap overrides important OSX defaults

### ISSUE THREAD

**Issue by ezzatron** [erichard/SublimePHPCompanion#21]
I use Sublime on both OSX and Linux, and whilst the default key bindings for PHP Companion work okay for Linux, they clash with some important things in OSX.

In particular:

- F4 is used to go to the next result in a multi-file search
- F5 is used to sort lines
- F6 (and variants) are used for spellcheck related functions

I remap import_namespace to F8 and find_use to F10 as they're unused, but I also have to re-map F4, F5, and F6 back to their defaults which is pretty annoying.

Perhaps some better defaults could be chosen? At least for OSX, although personally I prefer it when keybindings work in an equivalent way across platforms. What do you think?

**Comment by erichard** [comment]
Fixed by removing all keymaps as @iamntz advice me a year ago :smile:
