### ISSUE TITLE
make import_namespace detect composer.json 

### ISSUE THREAD

**Issue by rawaludin** [erichard/SublimePHPCompanion#30]
Hi, thanks for this great plugin. It really help me building Laravel app. I have a sugestion. Is is possible for this plugin to read a configuration for namespace in `composer.json` file?

When using Laravel, default composer.json autoload told that all folder in App directory should be namescaped in `app`. But, when I use import_namespace this plugin give a full directory url. 

Eg. when I run from `/User/me/Code/laravel/app/entity/model.php`. It should be `App\Entity\Model` based on composer.json autoload configuration.
But, it give me `User\me\Code\laravel\app\entity\model`.

Here is sample composer.json files:

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "laravel/framework": "5.0.*",
        "league/commonmark": "0.7.*",
        "barryvdh/laravel-ide-helper": "~2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

The configuration for namespace is this line:

```
....
       "psr-4": {
            "App\\": "app/"
        }
....
```

**Comment by erichard** [comment]
Hi, the default pattern for namespace resolution is to start at the first CamelCased folder. So your `/User` is detected to be the first one.

I will take a look if I can use composer configuration, it may be a good idea. For now, you can ajuste the `start_dir_pattern` and give a regex that satisfy your need.

**Comment by valeryan** [comment]
I would love to see this package support psr-4. I was able to get pretty close using the per project namespace prefix setting and a modified regex to look for src (the folder I always put my package code into). I can get it to work fine for files in a sub directory under src for example in `src\Directory\File.php` I get `namespace Vendor\Package\Directory;` but if the file is in the root `src\File.php` I get the prefix with a \ on the end `Vendor\Package\;`. I can't figure out why the root files get the slash...

This is what I put in my project files:
```
"phpcompanion": {
        "start_dir_pattern": "^(?:.*?src)(.*)$",
        "namespace_prefix": "Vendor\\Package"
    }
```
Anyway maybe someone can figure out how to fix the small `\ ` problem with this example and it would work for psr-4 package development.

**Comment by Luddinus** [comment]
Any news?

**Comment by erichard** [comment]
@Luddinus I'm pretty busy at this time. I will take a look as soon as possible. 

If someone want to work on this, I'm opened to PR.

**Comment by Luddinus** [comment]
@erichard Ok, thx.

My approach, not the best but, I separate the "package" in another project and then i use the "phpcompanion" config

**Comment by erichard** [comment]
PSR-4 support is quite a complicated task. Working on a file in the src/ folder is quite a simple use case but working in the vendor/ dir is much more complicated as it require to use the vendor composer.json file. 

I need to think a little more about this.

**Comment by ctf0** [comment]
i was just going to request the same thing, hopefully it gets added soon :+1:  :metal:

**Comment by coreation** [comment]
+1 :)

**Comment by subdesign** [comment]
Added to User Settings the following line and prefix is inserted before the generated part:
```
 "namespace_prefix": "App",
```

**Comment by flashios09** [comment]
@erichard 
First of all thanks for this awesome plugin, i'm python **newbie**(i don't know anything about python before trying to customize some ST3 plugins), i tried to do some changes to your code and now it read the **composer.json**(only at the root of the project).

In **<my_project>.sublime-project**, we need the **project_path**(it must be an absolute path) key inside the **phpcompanion** scope e.g :
```json
{
    "phpcompanion": {
        "project_path": "/Volumes/Data/Sites/hotelas"
    }
}
```

This is the code:
```python
import sublime
import sublime_plugin

import os
import re

import json

from ..settings import get_setting

class ImportNamespaceCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        # Filename to namespace
        projectPath = get_setting('project_path', '')
        filename = self.view.file_name().replace(projectPath, '')
        if filename.startswith('/'):
            filename = filename[1:]

        # Abort if the file is not PHP
        if (not filename.endswith(".php")):
            sublime.error_message("No .php extension")
            return

        # namespace begin at first camelcase dir
        namespaceStmt = os.path.dirname(filename)

        composer = (projectPath + '/composer.json').replace('//', '/')
        with open(composer) as composerFile:
            data = json.load(composerFile)

        for _replace_with, _path in data['autoload']['psr-4'].items():
            if _path.startswith('./'):
                _path = _path[2:]
            if namespaceStmt.startswith(_path):
                namespaceStmt = namespaceStmt.replace(_path, _replace_with)
                namespaceStmt = re.sub('/', '\\\\', namespaceStmt)
                namespaceStmt = namespaceStmt.strip("\\").replace('\\\\', '\\')
                break

        line_contents = "namespace " + namespaceStmt + ";"

        if "inline" == get_setting("namespace_position", "newline"):
            line_contents = " " + line_contents
        else:
            line_contents = '\n\n' + line_contents

        region = self.view.find(r"^(<\?php){0,1}\s*namespace\s[\w\\]+;", 0)

        if not region.empty():
            self.view.replace(edit, region, '<?php' + line_contents)
            return True

        region = self.view.find(r"<\?php", 0)
        if not region.empty():

            line = self.view.line(region)
            self.view.insert(edit, line.end(), line_contents)
            return True

```

**Comment by dakira** [comment]
Hey everyone. Picking this up. We can quite easily find the position of composer.json using this code:

```python
def get_active_project_path():
    import os
    window = sublime.active_window()
    folders = window.folders()
    if len(folders) == 1:
        return folders[0]
    else:
        active_view = window.active_view()
        active_file_name = active_view.file_name() if active_view else None
        if not active_file_name:
            return folders[0] if len(folders) else os.path.expanduser("~")
        for folder in folders:
            if active_file_name.startswith(folder):
                return folder
        return os.path.dirname(active_file_name)

def get_composer():
    import os.path
    import json
    composer = get_active_project_path() + '/composer.json'
    if os.path.isfile(composer):
        return json.load(open(composer))
    else
        return None
```

So that part works. I'm just not sure how the code by @flashios09 is supposed to work, but I'm also not a Python programmer. It think the big problem here is getting this to work for Windows and Linux/Mac. If you ask me, lets just focus and Linux/Mac for the time being. ;)

**Comment by ragboyjr** [comment]
Just my two cents, with composer, I usually specify an autoload and autoload-dev like so:

```
{
  "autoload": {
    "psr-4": {
      "Acme\\Foo\\": "src"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Acme\\Foo\\Test\\": "test"
    }
  }
}
```

I can set the namespace prefix to `Acme\Foo`, however, this wouldn't work for the tests directory because it would be missing the Test part of the prefix.

Btw, this plugin is amazing! I'd love to contribute for this feature, if it's something you feel like you'd want to support.

@erichard

**Comment by lyrixx** [comment]
Yeah, supporting the composer.json is really a need ;). I could help also. Just tell us.

**Comment by Arcesilas** [comment]
> PSR-4 support is quite a complicated task. Working on a file in the src/ folder is quite a simple use case but working in the vendor/ dir is much more complicated as it require to use the vendor composer.json file.

No one should never EVER work in the vendor directory. The only `composer.json` that needs to be read is the one at root of the project.

We're not talking about completion (completion packages use `vendor/autoload.php`, not `composer.json`).

**Comment by erichard** [comment]
Great news everybody ! 

I finally get it working thanks to code provided by  @flashios09 and @dakira. 

I will tag this as 2.0 as it's a huge step forward. You can try the 2.0 release by cloning this repository and checkout the `psr4-support` branch. 

I will test it for a couple of days/weeks before release.

**Comment by erichard** [comment]
Everything is fine so far. I will release this before christmas as a gift for all of us. :gift:

**Comment by dakira** [comment]
This is great, thanks for maintaining my favorite ST plugin!
