### ISSUE TITLE
Automatically insert find_use 

### ISSUE THREAD

**Issue by moon0326** [erichard/SublimePHPCompanion#32]
I'm sure there's a reason why this feature is not implemented, but I'm not sure of it.

It would be extremely nice to have a command (in the package) to find all the classes in a file then insert use automatically. If there're multiple files with the same name, then a dialog pops up.

Am I missing something?

**Comment by erichard** [comment]
This feature is quite hard to implement. 

First we need to get all classes in a file, the Sublime index store symbols not class, so I have no direct way to extract all classes in the file in python. I could delegate that to some kind of PHP scripts maybe but not so sure...

Also there is some use cases that woulb be hard to deal with. Like this one:
```php
// Symfony\Component\HttpFoundation\Request
$request = new Request();

// GuzzleHttp\Psr7\Request as GuzzleHttpRequest
$guzzleRequest = new GuzzleHttpRequest()
```

So I will not work on this for now. But PR are welcome :smiley:

**Comment by moon0326** [comment]
That makes sense. Okay! I will research further if there's any possibilities to implement it. Thank you for the answer and the plugin :)

**Comment by simplenotezy** [comment]
That was the only reason I downloaded this package, because I hoped it was here. I believe something like Phpstorm does this out of the box

**Comment by erichard** [comment]
Just stick with PHPStorm then…
