### ISSUE TITLE
Inconsistent keybindings / readme

### ISSUE THREAD

**Issue by anlutro** [erichard/SublimePHPCompanion#33]
I was super confused as to why the keyboard shortcuts described in the readme weren't doing anything. Apparently the readme assumes everyone is on OSX by default, because I finally thought to look in the sublime-keymap files, upon which I realized that Linux uses a different set of keys than OSX.

I'd suggest making the keybindings the same everywhere, but at the very least the readme should clarify what the keybindings are on the different OSes.

**Comment by erichard** [comment]
I've fixed the readme with the correct shortcut. 

I wish I could get all users on the same keybindings but I think all OSX users will hate me really soon if I revert to F4-F5-F6. The alternative option is to change shorcut for everyone and make everyone hate me :smile:

**Comment by anlutro** [comment]
Sensible enough! Thanks.

**Comment by erichard** [comment]
@anlutro I just removerd all keymaps. 

I try to use the messaging feature of packagecontrol to warn every users.
