### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by Fuxy22** [erichard/SublimePHPCompanion#35]
I'm on windows 7 64bit and the key binding are missing from Preferences > Package Setting > PHP Companion.

Using the keyboard shortcuts doesn't work.

Doing `Ctrl + Shift + P` searching for 'PHPCompanion' and running the commands from there does work tough.

**Comment by Fuxy22** [comment]
Never mind I just notice you removed them intentionally.

May i ask why? 

I find it more neat to have the keyboard shortcuts defined per plugin instead of the global user keybindings.

**Comment by erichard** [comment]
Hi,

It's all explained in [this message] (messages/1.0.0.txt). But for a reason I ignore package controle does not want to show it...

**Comment by sebdesign** [comment]
@erichard the message you are linking to returns a 404.

**Comment by erichard** [comment]
@sebdesign Fixed it

**Comment by sebdesign** [comment]
@erichard cheers!
