### ISSUE TITLE
TypeError with insert_php_constructor_property

### ISSUE THREAD

**Issue by cmpex** [erichard/SublimePHPCompanion#37]
As a follow up to my previous issue, seeing this error when attempting to use the insert constructor property function.

Also, I updated my user keybinding to "insert_php_constructor_property" since that looks like it was just updated.

```
Traceback (most recent call last):
  File "F:\dev\sublimetext\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "php_companion.commands.insert_constructor_prop in F:\dev\sublimetext\Data\Installed Packages\PHP Companion.sublime-package", line 30, in run
  File "php_companion.commands.insert_constructor_prop in F:\dev\sublimetext\Data\Installed Packages\PHP Companion.sublime-package", line 50, in add_property
TypeError: Can't convert 'NoneType' object to str implicitly
```

Here is the code I'm trying to test this on:
```
<?php

class BaseClass {
   public function __construct($testVar) {
       print "In BaseClass constructor\n";
   }
}
```

Thanks again!

**Comment by erichard** [comment]
@anlutro Can you take a look ?

**Comment by anlutro** [comment]
I'm guessing it's this:

https://github.com/erichard/SublimePHPCompanion/blob/0488b2073b29f6155b1c570319aa81f001fc4b6e/php_companion/commands/insert_constructor_prop.py#L50

Which means that `self.visibility == None`. Is it possible that the `default` argument of `get_setting` doesn't work as it should? The call to `self.visibility = get_setting()` is here:

https://github.com/erichard/SublimePHPCompanion/blob/0488b2073b29f6155b1c570319aa81f001fc4b6e/php_companion/commands/insert_constructor_prop.py#L28

@cmpex I think you should be able to fix your issue by adding `"visibility": "private"` to the package config file.

**Comment by cmpex** [comment]
That line was already in the user settings for PHP Companion.

Added it to the default config file as well to no avail.

Still seeing the same error.

thx
