### ISSUE TITLE
Import all required methods of an interface or abstract class

### ISSUE THREAD

**Issue by erichard** [erichard/SublimePHPCompanion#39]
Hard to solve problem as it require PHP introspection.

**Comment by anlutro** [comment]
Regexes should be able to handle this, provided we can get the path to the interface/abstract class.

You might not be able to do a "implement all abstract/interface methods for this class", but you could attempt to find the interface/abstract class the user has their cursor over, try and find the file (in the same way `find_use` does) and then use regex to figure out what methods to implement.

The trickiest bit would be making sure not to find matches inside comments (could remove them with `re.sub` before searching for matches), and abstract functions' `abstract` keyword can come in any position along with the optional visibility and `static` keywords.

**Comment by kkiernan** [comment]
I saw this feature in Visual Studio when working on a C# project and immediately thought it would be awesome in PHP Companion. Have you looked into it any further?

**Comment by kkiernan** [comment]
I did a quick bare bones version just to test the idea. [Here's a standalone gist](https://gist.github.com/kkiernan/bc562611cbc8bb3c9b62) if you'd like to take a look. I just setup a key binding for the `generate_inteface_methods` command to test it.

**Comment by erichard** [comment]
@kkiernan Thank for the gist ! I will try your command for few days.

**Comment by kkiernan** [comment]
The [updated gist](https://gist.github.com/kkiernan/bc562611cbc8bb3c9b62) has been working pretty well for me. @erichard did you get a chance to try it out? Would love to see what you think.

**Comment by erichard** [comment]
I haven't try the new gist. I will try it this week.

**Comment by kkiernan** [comment]
Just opened a new pull request for this feature. If you get to check it out let me know what you think or if I can help implement this idea in some other way. I think it's a pretty cool little feature.

**Comment by erichard** [comment]
Landed in v1.2.0. Thank @kkiernan !
