### ISSUE TITLE
Integrate with Padawan.php

### ISSUE THREAD

**Issue by mkusher** [erichard/SublimePHPCompanion#46]
What do you think about adding php-completion with a help of [padawan.php project](https://github.com/mkusher/padawan.php)? I've made a [plugin for st3](https://github.com/mkusher/padawan.sublime), but we can integrate it with yours directly.

**Comment by erichard** [comment]
I didn't know the padawan project but it seems very nice ! 

I'm very welcome to integrate your plugin in PHPCompanion. Could you make a PR ?

**Comment by mkusher** [comment]
@erichard ok, I'll try to send PR next week(24-30) :+1:

**Comment by mkusher** [comment]
Now in st3 plugin there are commands(caption in palette, command name):
1. `Padawan: Start Server`, `padawan_start_server`
2. `Padawan: Restart Server`, `padawan_restart_server`
3. `Padawan: Stop Server`, `padawan_stop_server`
4. `Padawan: Add plugin`, `padawan_plugin_add`
5. `Padawan: Remove plugin`, `padawan_plugin_remove`
6. `Padawan: Generate Index`, padawan_generate_index`

And settings items:
1. `padawan_composer_command`
2. `padawan_timeout`

Have you some naming convention or I can use same names?

**Comment by mkusher** [comment]
2 more questions: now I add padawan.php as a git submodule to editors' plugins, do you know other ways? If no, where should I put this stuff? 
Padawan.php requires additional steps in installation process, see: [install.sh](https://github.com/mkusher/padawan.sublime/blob/master/install.sh)
What do you think about it?
Sorry for so many questions :)

**Comment by erichard** [comment]
Keep thoses commands names, it' fine.

**Comment by erichard** [comment]
I think you should separate the server from the plugins. The server itself could be installed with `composer global` command. Some steps I would perform :
 - Rename cli to padawan, this way we all have a padawan command to manipulate the server
 - Remove the .php from the package name and call it `mkusher/padawan`
 - Tag a stable version 
 - Publish to packagist

The server install process will be pretty simple with :
    $ composer global require mkusher/padawan
    $ padawan start

Plugins will require options such as `padawan_server_host` and `padawan_server_port` to communicate with the server.

This architecture will make server and plugins more independant.

What do you think ?

**Comment by mkusher** [comment]
@erichard I thought about separation, but a little bit different way: install padawan as a editor's plugin dependency via composer. The main problem with global installation is extensions(plugins) management, because editor's plugin should install composer package by themself and then run padawan's `plugin add` command, I'm not sure it it will work with global installation. I'm not sure, that plugins management now have been done right also

**Comment by erichard** [comment]
Not sure about installing padawan plugin from sublime text. For now if you use both sublime and vim, you have padawan installed twice and each instance has its own plugins. It's a bit strange for a client/server architecture...

**Comment by mkusher** [comment]
@erichard yeah. I'll try doing some research

**Comment by mkusher** [comment]
@erichard hi! I've released [padawan package on packagist](https://packagist.org/packages/mkusher/padawan), so now I'll start working on the integration with your plugin.

**Comment by erichard** [comment]
@mkusher Great ! Tell me if you need help.
