### ISSUE TITLE
I can't find this package in Sublime3!

### ISSUE THREAD

**Issue by hgolov** [erichard/SublimePHPCompanion#47]

**Comment by erichard** [comment]
Do you have installed package control? You can find my plugin by searching for "PHP Companion" in the install package command (ctrl + shift + p then type install)

**Comment by hgolov** [comment]
Thank you. I was looking for the entire text - Sublime PHP Companion and it
didn't show up, but just PHP Companion did.

Have a great day,
Hadassa Golovenshitz
