### ISSUE TITLE
IDEA: insert_namespace custom prefix

### ISSUE THREAD

**Issue by rweas** [erichard/SublimePHPCompanion#52]
This would be especially useful for Laravel applications and I don't feel like it would be very hard to implement, but I have no idea how Sublime packages work so I cannot develop it. 

Basically, in your PHP Companion.sublime-settings you could set a prefix, for example "App" for a laravel app. So when you hit f10 you will get `App\Http\Controllers\FooController` instead of `Http\Controllers\FooController`

Awesome work on this project! It's saved me so much time!!!

**Comment by ctf0** [comment]
am having the same thing and i believe the current solution would be makeing a project file and add the setting of namespace_prefix ,however this is also connected to this issue
https://github.com/erichard/SublimePHPCompanion/issues/30

**Comment by erichard** [comment]
With PSR-4 support recently added. I think we don't need this anymore.
