### ISSUE TITLE
insert_php_constructor_property not available

### ISSUE THREAD

**Issue by lukeed** [erichard/SublimePHPCompanion#53]
Hi there,

Upon searching for available PHP Companion commands, there's no mention of any constructor action.

Just in case there wasn't supposed to be, I went into my keymapping & set up a keybind to the "insert_php_constructor_property" command.

Nothing happens. No Console message either. Every other command (and keybind) works like a charm.

**Comment by erichard** [comment]
Hi @lukeed 

I use this keybinding and it work fine. 
`{ "keys": ["f7"], "command": "insert_php_constructor_property" }`

Do you still have the problem ?

**Comment by lukeed** [comment]
I had that at at the time, and it was still unresponsive.

**Comment by sean-caddell** [comment]
I too am having this issue, running sublime text 3.

	{ "keys": ["f8"], "command": "insert_php_constructor_property" },
	{ "keys": ["f9"], "command": "expand_fqcn" },
	{ "keys": ["f10"], "command": "find_use" },

f8 does nothing at all, it is not bound to any other key, I have tried shift+ combination but no joy.

Any ideas would be helpful :)

**Comment by erichard** [comment]
@sean-caddell @lukeed Could you try with `insert_constructor_prop` ?

**Comment by sean-caddell** [comment]
{ "keys": ["f8"], "command": "insert_constructor_prop" },
	{ "keys": ["f9"], "command": "expand_fqcn" },
	{ "keys": ["f10"], "command": "find_use" },

This is so strange :) Not sure if it is some kind of indexing problem but I added the line above but it made no difference. So I searched for the functionality using ctrl+shift+p and saw it listed I then did the following

	{ "keys": ["f8"], "command": "insert_constructor_prop" },
	{ "keys": ["shift+f8"], "command": "insert_php_constructor_property" },
	{ "keys": ["f9"], "command": "expand_fqcn" },
	{ "keys": ["f10"], "command": "find_use" },

then did a search again using ctrl+shift+p and suddenly the function was listed with the shortcut key next to it. So it is now working!

	{ "keys": ["shift+f8"], "command": "insert_php_constructor_property" },
	{ "keys": ["f9"], "command": "expand_fqcn" },
	{ "keys": ["f10"], "command": "find_use" },

I love this function btw :)

**Comment by erichard** [comment]
I've renamed the command to match ST convention. Hope it help

**Comment by mustafawm** [comment]
Hi,

I'm using ST3 on Mac OS Sierra. 

I've tried the following, but no success! 

```
{ "keys": ["f7"], "command": "insert_php_constructor_property" },
{ "keys": ["f7"], "command": "insert_constructor_prop" },
```

Any advice?

**Comment by erichard** [comment]
Still having problem on this ?

**Comment by lukeed** [comment]
I'm no longer using this plugin (or PHP in general) but perhaps this issue should stay open for the others who experienced this as well? They can confirm/deny any changes.

**Comment by mustafawm** [comment]
Yes. 
MacOS Sierra. ST3 build: 3126

Key bindings:
```
{ "keys": ["f4"], "command": "import_namespace"},
{ "keys": ["f9"], "command": "expand_fqcn" },
{ "keys": ["f10"], "command": "find_use" },
{ "keys": ["f7"], "command": "insert_php_constructor_property" },
``` 
It even doesn't show up when searching for `phpcompanion` commands in `cmd+shift+p`

![screen shot 2017-01-28 at 8 33 59 pm](https://cloud.githubusercontent.com/assets/13101565/22395720/081971fa-e59a-11e6-9632-a1de49e052db.png)

**Comment by loganbecket** [comment]
I'm seeing this same issue where "insert_php_constructor_property" simply doesn't appear, but the other five do.  It was working at one time and then mysteriously disappeared.
