### ISSUE TITLE
Can't get working expand_fqcn

### ISSUE THREAD

**Issue by burdiyan** [erichard/SublimePHPCompanion#54]
Hello,

I have fresh Sublime Text 3 installation. Build 3083. I have installed PHP Companion and started fresh Laravel 5 project, and I can't get `expand_fqcn` command to work.

I tried to call it with key bindings I previously set up, and also via Command Palette, and nothing happens. I have tried to do that with different classes and different use cases. Just nothing is happening.

Import namespace and create constructor properties are working.

Can't figure out what it can be.

Thanks!

**Comment by erichard** [comment]
Hi @burdiyan,

`expand_fqcn` need to be called after ST has generated a full index. It means that you need to open a folder a not a single file. Then you put the cursor over a classname and trigger the command.

Have you done this ?

**Comment by burdiyan** [comment]
Hi @erichard,

Yes, that is exactly what I was doing. But it is not doing anything. Do you know if there is any way to rebuild sublime text indexes? May be that could be the issue.

Thanks.

**Comment by erichard** [comment]
You may have a corrupted index, try this:
 - Close ST
 - Delete the ~/.config/sublime-text-3/Index folder
 - Open ST

It should reindex itself but you can force an index generation by hitting  Goto > Goto Symbol in Project in the menu.

**Comment by burdiyan** [comment]
@erichard removing indexes did the trick! Thanks a lot!
