### ISSUE TITLE
importing the correct class name in USE.

### ISSUE THREAD

**Issue by ctf0** [erichard/SublimePHPCompanion#55]
currently am having a small issue when trying to import the class name for something like `Faker\Factory` so instead i get `use Faker\Faker` and here is a ss to show what i get

![faker](https://cloud.githubusercontent.com/assets/7388088/11459202/f4c87c00-96d9-11e5-847a-b978f9e60106.png)

**Comment by erichard** [comment]
Maybe you have the cursor on `Faker` instead of `Factory` ?

**Comment by ctf0** [comment]
actually yes but i mean when the class get imported shouldn't it be `Faker\Factory, Faker\Generator, etc...` ?

**Comment by erichard** [comment]
The use statement is made by concatening the namespace defined in the file you choose and the symbol the cursor is over. So you get `Faker\Faker` because all files you can choose have a `Faker` namespace and you have cursor on `Faker` symbol. 

Hope I was clear enough :)

**Comment by ctf0** [comment]
okay i got it, would there be anyway to implement something that if the namespace was the same like in the above ss, it would then have the first segment `Faker` then add the file class name like `Generator' ?

**Comment by erichard** [comment]
I don't really want to change a working feature. Just remember to always have the cursor on the last symbol in the FQCN and it will work in any case.

**Comment by ctf0** [comment]
okay np, thanx :+1:
