### ISSUE TITLE
Import Trait with find_use

### ISSUE THREAD

**Issue by qkdreyer** [erichard/SublimePHPCompanion#57]
find_use can import class namespace but isn't working on traits for now

**Comment by erichard** [comment]
Yeah this is pretty annoying. The built in PHP syntax definition is a bit old. There is a PR that fix that in the official repository https://github.com/sublimehq/Packages/pull/22. 
So you could wait this PR get merged or use ST3 3095 with [php-grammar](https://packagecontrol.io/packages/php-grammar).
