### ISSUE TITLE
goto_definition_scope not taking into account the exclude_dir setting

### ISSUE THREAD

**Issue by bgatellier** [erichard/SublimePHPCompanion#58]
Hi,

I was just asking myself if this behavior is a feature or a bug.
I've just installed it, then I added a directory (``app/cache``) to the ``"exclude_dir"`` property of the package settings (using User settings).
I expected that the _goto_definition_scope_ takes in account this setting, but it seems that this command does not (it always suggest me a class from this folder). On the opposite, the _find_use_ command takes it into account as expected.

So I would like to know if this behavior is working as expected, or there is a way to exclude dir from the _goto_definition_scope_ command.

I am using ST on Windows 10.

**Comment by erichard** [comment]
Hi. This commande use the ST3 index. Try adding `app/cache` to the `index_exclude_patterns` options to exclude this directory.

**Comment by bgatellier** [comment]
That what I tried and it works perfectly, thanks.
I just found that having the package configuration in possibly several files is a bit difficult to apprehend.

I suggest to add this specific configuration in the documentation.
