### ISSUE TITLE
Shortcut not working

### ISSUE THREAD

**Issue by thisismyaim** [erichard/SublimePHPCompanion#60]
I just installed plugin and re-created index but still f9,f10 or other keys not working in sublime text 3 in preference menu showing : Change log, Readme and License options and in default key shortcut when i try to search f9 nothing shows. I used default shortcuts in user key settings but same issue no FQCN work or key.

**Comment by erichard** [comment]
Hi @thisismyaim. Do you have some error in the console view ?

**Comment by thisismyaim** [comment]
no error in console.

**Comment by Sarav-S** [comment]
Same here. Shortcuts not working on mac.

**Comment by ctf0** [comment]
this is mostly related to the latest versions of ST, for some reason it stopd working in here as well.

**Comment by ctf0** [comment]
this is mostly related to the latest versions of ST, for some reason it stopped working in here as well.

**Comment by ctf0** [comment]
same here :(

**Comment by erichard** [comment]
Are you all on OSX ? Which version of ST3 do you use ?

**Comment by Sarav-S** [comment]
I use Sublime Text 3 on Mac OS X 10.11 ( El Captain)

**Comment by ctf0** [comment]
OSX 10.11.3 , ST 3107

**Comment by ctf0** [comment]
good news, its fiex on the new release ST 3109.

**Comment by ctf0** [comment]
good news, its now fixed on the new release ST 3109.

**Comment by dashingd** [comment]
so is there any fix for this issue?

**Comment by thisismyaim** [comment]
I changed subl version to new and it's working fine
