### ISSUE TITLE
I can't find this package in Sublime3!

### ISSUE THREAD

**Issue by wedojava** [erichard/SublimePHPCompanion#61]
Hello
1. I have installed package control
2. I find your plugin by searching for "PHP Companion" in the install package command (ctrl + shift + p then type install)

than,I can't find this package in Sublime3!what happened?

**Comment by Liscus** [comment]
can't find phpcompanion in package control 
Sublime Build 3083

I have and can't find any solution.

**Comment by Liscus** [comment]
Hi wedojava,

I just installed it on sublime (build 3083), after installation, php companion didnt showed up anymore in package control, but under Browse Packages -> Installed Packages.

**Comment by wedojava** [comment]
thanks,i got it!
i don't know what happend.Now everything is back to normal
an issue told me that,linode is be attacted by DDOS.

**Comment by erichard** [comment]
More info on this DDoS in the package control repository: https://github.com/wbond/package_control/issues/1057
