### ISSUE TITLE
Padawan.php not work

### ISSUE THREAD

**Issue by zaknight** [erichard/SublimePHPCompanion#68]
"Padavan.php not running",
sublimetext stopped and lead to inactivity.

**Comment by adiachenko** [comment]
Yeah, the package is broken. In my case, it slows down Sublime to the point where I can't work anymore. I added PHP Companion to `ignored_packages` for now.

**Comment by michealharker** [comment]
I can confirm this is happening for me - but instead of slowing down ST3 it's instead completely locking it up and I can't do any more. I've had to kill the plugin_host process (which was using about 75% CPU), added "PHP Companion" to ignored_packages and now ST3 is not crashing.

**Comment by erichard** [comment]
Sorry guys, I just pushed a new version without padawan
