### ISSUE TITLE
using classes don't work, but methods work

### ISSUE THREAD

**Issue by alfredbez** [erichard/SublimePHPCompanion#75]
I'm working on a [Symfony-project](https://github.com/symfony/symfony) and I installed my project via the [symfony-installer](https://github.com/symfony/symfony-installer)
```
$ symfony new debugSublime
```

When I try to import the [`Request`-class](https://github.com/symfony/symfony/blob/b85ab60b70f0dcff62ac8438e91e7a93c44823da/src/Symfony/Component/HttpFoundation/Request.php#L29) in one of my files it fails, however typing `createFromGlobals` and running the `find_use` command generates `use Symfony\Component\HttpFoundation\createFromGlobals;` which [is only a method](https://github.com/symfony/symfony/blob/b85ab60b70f0dcff62ac8438e91e7a93c44823da/src/Symfony/Component/HttpFoundation/Request.php#L265), not a class.

I took a look in the index via `Goto` > `Goto Symbol in Project...`. The symbol `createFromGlobals` is in my Index, but `Request` is missing.

I closed Sublime Text deleted the index (`rm -rf ~/.config/sublime-text/Index`) and open it again, same result.

Path to `Request` in my project: `/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Request.php`.

Here is my demo-code:
```php
<?php

namespace AppBundle\Controller;

use Symfony\Component\HttpFoundation\createFromGlobals;

class DefaultController extends Controller
{
    public function indexAction()
    {
        $request = new Request;
        $qhy = new createFromGlobals;
    }
}

```

---
Am I doing something wrong?

**Comment by erichard** [comment]
How do you run the `find_use` command ?

**Comment by alfredbez** [comment]
via the Command Palette

**Comment by kbsali** [comment]
exact same issue here

**Comment by erichard** [comment]
What build do you use ? Can you reproduce on last build ?

**Comment by kbsali** [comment]
3113

**Comment by kbsali** [comment]
Just upgraded to 3114 and same issue.

**Comment by erichard** [comment]
The plugin use the Sublime index, there is nothing much I can do about that... 

Maybe you can try this:
 1. Remove all your user settings
 2. Rebuild the index  with `rm -rf ~/.config/sublime-text/Index`
 3. Try to use `find_use` on a Request symbol

**Comment by kbsali** [comment]
sorry, i guess i spoke too fast.
I works again... not sure why though ! :)

If i ever get the issue again, i'll try purging the Indexes! :+1:

**Comment by erichard** [comment]
Great !

**Comment by alfredbez** [comment]
I tried the following:

1. Closed sublime-text
1. Deleted Index `$ rm -rf ~/.config/sublime-text/Index`
1. Backup Preferences`$ mv ~/.config/sublime-text-3/Packages/User/Preferences.sublime-setting{s,s.backup}`
1. Open project again `$ subl .`
1. `Goto` > `Goto Symbol in Project...`
1. same problem

Build 3113

**Comment by kbsali** [comment]
@alfredbez have you tried upgrading to 3114?

**Comment by Daursu** [comment]
I have the same problem on 3114. I've tried to clear the Indexes and Cache and rebuild everything, but the class names were not indexed.

I've downgraded to 3103 for now and that works fine.

**Comment by alfredbez** [comment]
@kbsali Upgrading to 3114 fixed it for me, thanks.

**Comment by gmhenderson** [comment]
Updating to 3114 and deleting the Index at `~/Library/Application Support/Sublime Text 3/Index` worked for me on Mac.
