### ISSUE TITLE
Feature Request: Prune Unused Imports

### ISSUE THREAD

**Issue by JeffreyWay** [erichard/SublimePHPCompanion#77]
I'd love to see a command that automatically removes any unused classes that have been imported. 

For ex:

```php

namespace Yolo;

use Bar;
use Thing;
use Baz;

class Foo {
  public static function go() {
    Bar::fire();
  }
}
```

If I run the "prune" command on this file, it would prune the `use Thing` and `use Baz` lines. So it would change to this:

```php

namespace Yolo;

use Bar;

class Foo {
  public static function go() {
    Bar::fire();
  }
}
```

**I'll contribute $200 (with Paypal) to whoever PRs or adds this.**

**Comment by nicholasruunu** [comment]
Possible problem areas to consider:
* Aliases
* Annotations

Don't know if you care about them though. :)

**Comment by wesbos** [comment]
I've been out of the PHP game for a while, but if anyone who is thinking about this here is some helpful info on Sublime Text Plugins.

Most tools like this have very little python and just shell out the task to a sub process - see this example where JSCS formatter uses node to run: https://github.com/TheSavior/SublimeJSCSFormatter/blob/master/JSCS-Formatter.py#L72-L86


Look like CS Fixer does this (again, not sure of tool quality, I'm not a big PHP dev anymore). https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by JeffreyWay** [comment]
Ahh okay, so it looks like 'unused_use' is not included in the main php-cs-fixer PSR2 fixer level. You have to add it on. 

For anyone interested, this is my PHP build file for Sublime.

```
{
    "shell_cmd": "php-cs-fixer fix $file --level=psr2 --fixers=unused_use"
}
```

So I hit command+b, and it formats it for PSR-2, and also strips unused imports.
