### ISSUE TITLE
Padawan Server Not Working

### ISSUE THREAD

**Issue by cjmellor** [erichard/SublimePHPCompanion#84]
Hi,

I'm trying to use the padawan server with this plugin, but I have no idea how to get it working, or even if it is working to begin with.

I've globally required the padawan package in composer, and this works by running `padawan-server` in the Terminal.

I've now added some config to the `Default (OSX).sublime-keymap` file like so:

``` json
{ "keys": ["command+ctrl+o"], "command": "padawan_generate_index" },
```

But this doesn't do anything - like no output and not even sure if it's generating anything.

Is there anything in particular that needs adding to make this work correctly?

**Comment by erichard** [comment]
Hi @cjmellor 

I have disabled Padawan integration due to a high CPU problem (see #68). 

I will look for a better and less coupled integration for this someday.

**Comment by golaod** [comment]
I have a big question. Basic padawan doesn't work at all now, you disabled padawan in your plugin, so is there any alternative to get it working?

**Comment by erichard** [comment]
@golaod You could try the plugin made by the padawan creator: https://github.com/mkusher/padawan.sublime

I may reintegrate padawan if the segmentation fault is fixed (see https://github.com/mkusher/padawan.php/issues/42)

**Comment by golaod** [comment]
That's why I wrote 'basic padawan doesn't work', because I also tried mkusher/padawan.sublime. Well, looks like I have to wait. Thanks :)
