### ISSUE TITLE
Custom package location

### ISSUE THREAD

**Issue by keevitaja** [erichard/SublimePHPCompanion#87]
Hello!

I am working on some custom packages for a Laravel project and they are located in

`packages/vendor/name/src` 

Can i configure companion to automatically import namescpaces for that? `namespace Vendor\Name` would be the namespace for the src folder in the example above.

**Comment by erichard** [comment]
Hello @keevitaja

I'm afraid you can't. All you can do is set a specific prefix for an entire project with `namespace_prefix`.
I guess you fall into the #30 feature request.
