### ISSUE TITLE
use StdClass

### ISSUE THREAD

**Issue by tdolph** [erichard/SublimePHPCompanion#90]
Hello

Is it possible to make it so it would also use StdClass when doing find_use command?

**Comment by erichard** [comment]
It works if you use `stdClass`

**Comment by tdolph** [comment]
Yes, it obviously works if you manually write it but i meant that PHPCompanion could do it for me.

**Comment by erichard** [comment]
I don't understand your problem. 

```php
<?php
namespace Test;

class Example {

    public function __construct() {
        $thing = new stdClass(); // the find_use here will work
        $otherThing = new StdClass(); // find use here won't work because of the typo
    }
}
```

**Comment by tdolph** [comment]
Im sorry if i have not been clear. I use keyboard shortcut (when i have cursor on a class name) to auto use it at the very top of the file and sort all uses. `{ "keys": ["ctrl+shift+u"], "command": "find_use" }` It works well... except when i put `$i = new stdClass;` to somewhere in the code and then try the same shortcut on it, the `use stdClass;` wont appear at the top of the php file like it does with all regular classes. So, i have to scroll to the top of the file and write it manually every time. If this is an error in my end then what can i do to fix it?

**Comment by erichard** [comment]
Do you have enabled the `allow_use_from_global_namespace` option in your config ?

**Comment by tdolph** [comment]
This is what i was missing. Thank you :) It works now. Sorry for wasting your time.

**Comment by erichard** [comment]
No problem :)
