### ISSUE TITLE
`use TraitName` breaks find_use command.

### ISSUE THREAD

**Issue by g105b** [erichard/SublimePHPCompanion#93]
When there are traits in use within a class, the `find_use` command is broken.

This is due to the `use` keyword having more than one meaning, dependent on context. One meaning is to "import" or "alias" a namespaced class. Another meaning is to "insert" a trait, and another meaning is to import a variable from an outer scope.

It seems that SublimePHPCompanion's `find_use` command is only taking the first meaning into account. It feels like the command simply looks for the nearest `use` keyword and adds the imports there. If a `use` keyword exists inside a class definition, everything breaks causing syntax errors.

**Comment by erichard** [comment]
Not sure I understand the problem. The plugin add the use statment after the namespace declaration. 

You want the plugin to do something else ?

**Comment by g105b** [comment]
There is a bug in the logic.

```php
<?php
namespace Test;

class Example {

    public function __construct() {
        $thing = new Thing(); // find use here is fine.
    }
}
```

```php
<?php
namespace Test;

class Example {

    use SomeTrait;
    use AnotherTrait;

    public function __construct() {
        $thing = new Thing(); // find use here breaks things because of the traits.
    }
}
```

**Comment by erichard** [comment]
I just tried your use case and the use statement is added at the right place and does not break anything.

Can you show me what you expect when using `find_use` in the second case ?

**Comment by g105b** [comment]
This is what I expect:

```php
<?php
namespace Test;

use \some\namespace\Thing; // added here by `find_use`.

class Example {

    use SomeTrait;
    use AnotherTrait;

    public function __construct() {
        $thing = new Thing(); // find use here breaks things because of the traits.
    }
}
```

This is what I actually get:

```php
<?php
namespace Test;

class Example {

    use \some\namespace\Thing; // it is actually added here - as if it were a trait.    
    use SomeTrait;
    use AnotherTrait;

    public function __construct() {
        $thing = new Thing(); // find use here breaks things because of the traits.
    }
}
```
