### ISSUE TITLE
Is it working for ST3 3126?

### ISSUE THREAD

**Issue by jgrossi** [erichard/SublimePHPCompanion#98]
Hey,

I'm trying this plugin but it seems it's not all working on Sublime Text 3 build 3126. I already configured the `keymap`.

It seems the `Insert Construct Property` command is the only one working.

Any issue like this before?

Thanks, JG

**Comment by DCzajkowski** [comment]
I can confirm. After updating to stable 3.0 release build 3143 PHP Companion stopped working. The only working command is `Insert Construct Property` as stated above 😢

**Comment by erichard** [comment]
Can you try this

1. Close ST3
2. Delete `~/.config/sublime-text-3/Index` folder
3. Open a folder/project in ST3

**Comment by DCzajkowski** [comment]
The folder `~/.config/sublime-text-3` doesn't exist for me...

**Comment by DCzajkowski** [comment]
Ok, never mind. After closing and reopening Sublime the plugin started working again. Thanks 👍
